server:
  port: 9000
lxt:
  server: http://localhost:${server.port}
# 文件上传相关配置
file:
  path:
    upload: D:/qcby/  #文件上传存储位置，不存在会自动创建
    prefix: /filePrefix/  #必须 / 结尾
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
