spring:
  redis:
    host: 127.0.0.1
    port: 6379
    # lettuce客户端
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制
        max-wait: 20
        # 连接池中的最小空闲连接
        min-idle: 5
